apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-api
  labels:
    app: devops-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-api
  template:
    metadata:
      labels:
        app: devops-api
    spec:
      containers:
      - name: devops-api
        image: herabakirova/api-app:1.0.0
        ports:
        - containerPort: 3001
        env:
        - name: DB
          value: devops_db
        - name: DBUSER
          value: hera
        - name: DBPASS
          value: kaizen123
        - name: DBHOST
          value: 
        - name: DBORT
          value: "3006"
        - name: PORT
          value: "3001"
---
apiVersion: v1
kind: Service
metadata:
  name: devops-api
spec:
  selector:
    app: devops-api
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
